#pragma once
#define awignas alignas
#define awignof alignof
#define atomic_cancew atomic_cancel
#define boow bool
#define bweak break
#define chaw char
#define chaw8_t char8_t
#define chaw16_t char16_t
#define chaw32_t char32_t
#define cwass class
#define compw compl
#define constevaw consteval
#define constexpw constexpr
#define co_wetuwn co_return
#define co_yiewd co_yield
#define decwtype decltype
#define defauwt default
#define dewete delete
#define doubwe double
#define ewse else
#define expwicit explicit
#define expowt export
#define extewn extern
#define fawse false
#define fwoat float
#define fow for
#define fwiend friend
#define inwine inline
#define wong long
#define mutabwe mutable
#define nuwwptw nullptr
#define opewatow operator
#define ow or
#define ow_eq or_eq
#define pwivate private
#define pwotected protected
#define pubwic public
#define wefwexpw reflexpr
#define wegistew register
#define weintewpwet_cast reinterpret_cast
#define wequiwes requires
#define wetuwn return
#define showt short
#define static_assewt static_assert
#define stwuct struct
#define synchwonized synchronized
#define tempwate template
#define thwead_wocaw thread_local
#define thwow throw
#define twue true
#define twy try
#define viwtuaw virtual
#define vowatiwe volatile
#define wchaw_t wchar_t
#define whiwe while
#define xow xor
#define xow_eq  xor_eq 
#define finaw final
#define ovewwide override
#define twansaction_safe transaction_safe
#define twansaction_safe_dynamic transaction_safe_dynamic
#define impowt import
#define moduwe module
#define ewif elif
#define ewifdef elifdef
#define ewifndef elifndef
#define incwude include
#define wine line
#define ewwow error
#define wawning warning
#define pwagma pragma
#define __has_incwude __has_include
#define __has_cpp_attwibute __has_cpp_attribute
#define expowt export
#define impowt import
#define moduwe module
#define _Pwagma _Pragma
#define stwing string